### ISSUE TITLE
Using UCS8904B

### ISSUE THREAD

**Issue by dimitre** [Differentunic/UCS8904-Datasheet#1]
Hello @Differentunic did you have success driving it with NeoPixelsBus library?
I've tried recently with no success. I'm trying to gather more information and put in this repo here
https://github.com/dimitre/UCS8904B

**Comment by Differentunic** [comment]
Hi! 

Yes I have had success with driving the UCS890x chip. 

Please see https://github.com/Makuna/NeoPixelBus/issues/516 for NeoPixelBus, and https://github.com/Aircoookie/WLED/pull/3091 for a be all end all solution. I am currently using WLED to drive my UCS8904B leds
